version: '3.8'

services:
  rabbitmq:
    container_name: RabbitMQ
    image: rabbitmq:3.7.8-management
    ports:
      - "15672:15672"
      - "5672:5672" 
    environment:
      RABBITMQ_DEFAULT_USER: logUser
      RABBITMQ_DEFAULT_PASS: logPwd  

  jaeger:
    image: jaegertracing/all-in-one:1.22.0
    ports:
      - "6831:6831/udp"
      - "16686:16686"     

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd      
